from collections import defaultdict
from operator    import itemgetter

def commonSubstring(s, X):
    freq = defaultdict(int)
    for i in range(len(s) - X + 1):
        freq[s[i:i+X]] += 1
    return max(freq.iteritems(), key=itemgetter(1))

print commonSubstring("AYNBZEMCEYAAMURMNRWZBVIMUSYREYAAMUMOSCUHMRSZNHMWWEYAAMMDBNKDDCDFRYRSZEMVCDUZCGZBRSZWYMBZBNCHWZEYAAMNKUSZBRYYDZYHRSZWYYQSYWZUEKRRSNYKFSRSZWYFUYHRSZEMVCDEYAAMMDBUMORSZCDBCMDOSYSMBHCNZBBYRSZSMBJKUREMKFSRRSZVYIEYAAMRSYAMUEYAAMMDBOMUNKDDCDFRYOMNBRSZHYNZURBYRQYCDRCDFRSZNCHWZRSNYKFSRSZWYFUMDBMCACDFMRMAZBMWYDRSZVNZMURYHRSZCDBCMDEYAAMAYNBZEMCHCNZBBYRRSZCDBCMDHZWWEYAAMMDBUQNCDFCDFRYSCUHZZRRSZVYINMDRYRSZYQZDMNAUYHSCUAYRSZNMRRSZEMVCDBYYNBYRAZMDOSCWZJYUCMSEYAAMOSYSMBNKDRYRSZHYNRHYNMCBEYAAMNZRKNDZBOCRSMQMNRIYHUZRRWZNU", 5)
